source_url: ftp://ftp.geobc.gov.bc.ca/sections/outgoing/bmgs/FWA_Public/
dl_path: source_data
db_url: postgresql://postgres:postgres@localhost:5432/postgis
data_def: data_def.yml

# write log to file and/or to console
log_level: INFO
log_file: True
log_console: False
log_name: fwakit
log_filename: fwakit
